---
title: "Fantasy Football 2017"
author: "Stephen York"
date: "November 6, 2017"
output: 
  html_document:
    toc: true
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Fantasy-Football-Schedule-Analysis")
library(highcharter)
library(reshape2)
library(dplyr)
```

```{r mock data}
#mock data
data <- data.frame(
  team = letters[1:12],
  week1 = runif(n = 12, min = 70, max = 130),
  week2 = runif(n = 12, min = 70, max = 130),
  week3 = runif(n = 12, min = 70, max = 130),
  week4 = runif(n = 12, min = 70, max = 130),
  week5 = runif(n = 12, min = 70, max = 130),
  week6 = runif(n = 12, min = 70, max = 130),
  week7 = runif(n = 12, min = 70, max = 130),
  week8 = runif(n = 12, min = 70, max = 130),
  week9 = runif(n = 12, min = 70, max = 130),
  week10 = runif(n = 12, min = 70, max = 130),
  week11 = runif(n = 12, min = 70, max = 130)
)
```


```{r score table, echo=FALSE}

dat <- data 
colnames(dat) <- c("Team", "Week 1", "Week 2", "Week 3",
                   "Week 4", "Week 5", "Week 6", "Week 7",
                   "Week 8", "Week 9", "Week 10", "Week 11")
dat
```

##Score Comparison
```{r score comparison, echo=FALSE, warning = FALSE}


mdata <- melt(data, id.vars = "team")
teams <- unique(mdata$team)
for (p in teams){
  filtDat <- filter(mdata, team == p)
  assign(x = p, value = filtDat)
}

highchart() %>%
  hc_add_series("line", data = a, hcaes(x = variable, y = value, group = team))%>%
  hc_add_series("line", data = b, hcaes(x = variable, y = value, group = team))%>%
  hc_add_series("line", data = c, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = d, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = e, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = f, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = g, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = h, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = i, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = j, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = k, hcaes(x = variable, y = value, group = team), visible = FALSE)%>%
  hc_add_series("line", data = l, hcaes(x = variable, y = value, group = team), visible = FALSE)
  

```

##Transaction Activity
```{r transactions, echo=FALSE, warning=FALSE}
transactions <- openxlsx::read.xlsx("FF.xlsx", sheet = 2)
transactions$total <- rowSums(transactions[,c(2,3,5)])
transactions <- arrange(transactions, desc(Acquisitions))

highchart() %>%
  hc_xAxis(categories = transactions$team) %>%
  hc_add_series(data = transactions$Trades, type = "column", name = "Trades") %>%
  hc_add_series(data = transactions$Acquisitions, type = "column", name = "Acquisitions") %>%
  hc_add_series(data = transactions$Activate, type = "column", name = "Activations")%>%
  hc_title(text = "Transactions by Type")

```


##Alex
##Neil
##Stephen
##Tommy
##Leigh
##Kyle
##Charlie
##Kelsey
##Sam
##Doug
##Cooper
##Erik